### ISSUE TITLE
welch_psd() generates figure even if show = False

### ISSUE THREAD

**Issue by kissorsolya** [PGomes92/pyhrv#24]
Hi!
When I am processing my signal I need the returned frequency data, but not necessarily the figures. 
This code plots a nice figure in my notebook: 

result = fd.welch_psd(intervals, show = False)

Can you help with this? 

Thanks a lot for this package! 
Orsi

**Comment by mosh-shu** [comment]
Same problem here. This is because when you look at the `_plot_psd` function in the `frequency_domain` module which you can inspect [here](https://github.com/PGomes92/pyhrv/blob/master/pyhrv/frequency_domain.py), `plot=False` option only gets applied to the last line of `if show: plt.show()`. However, in Jupyter notebook with the `%matplotlib inline` option called, `plt.show()` gets called at every cell anyway, so the show=False wouldn't mean anything. The workaround is to 1) not call the `%matplotlib inline` magicword in your notebook or 2) use the mode='dev' option to not produce the figure.

**Comment by PGomes92** [comment]
Hi @kissorsolya,

thanks for using pyHRV!

As @mosh-shu has evaluated correctly (thanks for that btw!), when pyHRV runs functions with plotting features in 'normal' mode it always generates a plot figure. The `show=False` parameter only hides the plot. Your current project or setup might be calling matplotlib to show all the available plot figures at another point hence the reasons why your plots may appear.

If you want to prevent pyHRV from generating any plot figures at all, I'd recommend using the 'dev' mode as @mosh-shu suggested.

Thanks!
