### ISSUE TITLE
Big error in quickstart documentation

### ISSUE THREAD

**Issue by jdevoldere** [PGomes92/pyhrv#29]
```
import biosppy
import numpy as np
import pyhrv.tools as tools
from opensignalsreader import OpenSignalsReader 

# Load sample ECG signal & extract R-peaks using BioSppy
signal = OpenSignalsReader('./samples/SampleECG.txt').signal('ECG')
signal, rpeaks = biosppy.signals.ecg.ecg(signal, show=False)[1:3]

# Compute NNI
nni = tools.nn_intervals(rpeaks)
```

pyhrv.tools.nn_intervals() takes in `rpeaks (array): R-peak times in [ms] or [s]`.

The problem is that the rpeaks parameter returned by biosppy.signals.ecg.ecg() does **NOT** contain R-peak times in [ms] or [s], instead it contains the _integer indices_ of the R-peaks.

Our research team had been working with faulty HRV calculations for half a year before we just now noticed the issue...

**Comment by PGomes92** [comment]
Hi @jdevoldere,

thank you very much for using pyHRV and my apologies for this unfortunate and undesirable situation. Thank you for alerting for this issue so that other users could be aware of that and I hope that you were still in time to catch this error for your results.

You are correct, there is indeed a key error in the presented sample codes that appears to occur across multiple samples in pyHRV.

I am providing below the correct code which computes the R-peak locations based on the indices and the time vector provided by biopsy:

```
import biosppy
import numpy as np
import pyhrv.tools as tools
from opensignalsreader import OpenSignalsReader 

# Load sample ECG signal & extract R-peaks using BioSppy
signal = OpenSignalsReader('./samples/SampleECG.txt').signal('ECG')
t, signal, rpeaks = biosppy.signals.ecg.ecg(signal, show=False)[:3]

# Compute NNI
nni = tools.nn_intervals(t[rpeaks])
```

I will correct the sample codes with the next update. My apologies and thanks for the alert!
